from .for_update_report.update_mechanical_power_data import update_mechanical_power_data
from .for_update_report.update_airgap_flux_density_data import update_airgap_flux_density_data
from .for_update_report.update_airgap_flux_density_no_load_data import update_airgap_flux_density_no_load_data

def update_record(data_processor):
    update_mechanical_power_data(data_processor=data_processor)
    update_airgap_flux_density_data(data_processor=data_processor)
    update_airgap_flux_density_no_load_data(data_processor=data_processor)
    return True

